[project]
name = "tools"
version = "0.0.1"
description = ""
authors = [{ name = "ywg" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12,<3.13"
dependencies = [
    "pybind11_stubgen",
    "numpy>=1.20.0",
]
